name: prueba_vacante_app
description: "A new Flutter project."
homepage: https://github.com/Yash-Garg/RickandMorty-Dart-Wrapper

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.1.1
  flutter_mobx: ^2.0.0
  shared_preferences: ^2.0.0
  provider: ^6.0.0
  dio: ^5.4.2+1
  lints: ^3.0.0
  


  cupertino_icons: ^1.0.6
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.1.1
  build_runner: ^2.4.6
  

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true